#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "auth_utils.h"

char** getTotpCodes(const char* seed) {
    char command[512];
    const char *totpGeneratorPath = "/externalbrowser/totpGenerator.js";
    
    snprintf(command, sizeof(command), "node %s %s", totpGeneratorPath, seed ? seed : "");
    
    FILE *pipe = popen(command, "r");
    if (!pipe) {
        return NULL;
    }
    
    char buffer[1024];
    char *output = fgets(buffer, sizeof(buffer), pipe);
    pclose(pipe);
    
    if (!output) {
        return NULL;
    }
    
    char *newline = strchr(output, '\n');
    if (newline) *newline = '\0';
    
    char **codes = malloc(sizeof(char*) * 3);
    codes[0] = codes[1] = codes[2] = NULL;
    
    int count = 0;
    char *token = strtok(output, " ");
    while (token && count < 3) {
        codes[count] = malloc(strlen(token) + 1);
        strcpy(codes[count], token);
        count++;
        token = strtok(NULL, " ");
    }
    
    return codes;
}

void freeTotpCodes(char** codes) {
    if (!codes) return;
    for (int i = 0; i < 3; i++) {
        if (codes[i]) free(codes[i]);
    }
    free(codes);
}

void test_mfa_totp_authentication(void **unused) {
    SF_UNUSED(unused);

    SF_CONNECT *sf = snowflake_init();
    set_all_snowflake_attributes(sf);
    
    char *mfa_user = getenv("SNOWFLAKE_AUTH_TEST_MFA_USER");
    char *mfa_password = getenv("SNOWFLAKE_AUTH_TEST_MFA_PASSWORD");
    
    printf("DEBUG: MFA_USER = %s\n", mfa_user ? mfa_user : "NULL");
    
    if (!mfa_user || !mfa_password) {
        snowflake_term(sf);
        fail_msg("MFA environment variables not set - SNOWFLAKE_AUTH_TEST_MFA_USER and SNOWFLAKE_AUTH_TEST_MFA_PASSWORD required");
        return;
    }
    
    snowflake_set_attribute(sf, SF_CON_USER, mfa_user);
    snowflake_set_attribute(sf, SF_CON_PASSWORD, mfa_password);
    snowflake_set_attribute(sf, SF_CON_CLIENT_REQUEST_MFA_TOKEN, &(sf_bool){1});
          
    char** totpCodes = getTotpCodes("");
    
    if (!totpCodes) {
        snowflake_term(sf);
        fail_msg("No TOTP codes were generated by getTotpCodes() - test cannot proceed");
        return;
    }
    
    char lastError[1024] = {0};
    
    for (int i = 0; i < 3 && totpCodes[i]; i++) {
        printf("Trying TOTP code %d: %s\n", i + 1, totpCodes[i]);
        
        snowflake_set_attribute(sf, SF_CON_PASSCODE, totpCodes[i]);
        
        SF_STATUS status = snowflake_connect(sf);
        
        if (status == SF_STATUS_SUCCESS) {
            printf("MFA authentication successful with TOTP code %d\n", i + 1);
            
            snowflake_term(sf);
            
            sf = snowflake_init();
            set_all_snowflake_attributes(sf);
            snowflake_set_attribute(sf, SF_CON_USER, mfa_user);
            snowflake_set_attribute(sf, SF_CON_PASSWORD, mfa_password);
            snowflake_set_attribute(sf, SF_CON_CLIENT_REQUEST_MFA_TOKEN, &(sf_bool){1});
            snowflake_set_attribute(sf, SF_CON_PASSCODE, NULL); // Clear old TOTP - rely on cached MFA token

            printf("DEBUG: Attempting cache test (no TOTP) - should use cached MFA token\n");
            SF_STATUS cacheStatus = snowflake_connect(sf);
            
            if (cacheStatus != SF_STATUS_SUCCESS) {
                SF_ERROR_STRUCT* error = snowflake_error(sf);
                printf("DEBUG: Cache test failed - Code: %d, Message: %s\n", 
                       error ? error->error_code : -1, error ? error->msg : "Unknown error");
            }
            
            freeTotpCodes(totpCodes);
            assert_int_equal(cacheStatus, SF_STATUS_SUCCESS);
            printf("SUCCESS: MFA authentication and caching completed successfully\n");
            snowflake_term(sf);
            return;
        } else {
            SF_ERROR_STRUCT* error = snowflake_error(sf);
            const char* errorMsg = error ? error->msg : "Unknown error";
            snprintf(lastError, sizeof(lastError), "%s", errorMsg);
            
            printf("DEBUG: Full error details - Code: %d, Message: %s\n", 
                   error ? error->error_code : -1, errorMsg);

            if (strstr(errorMsg, "Invalid") || strstr(errorMsg, "TOTP") ||
                strstr(errorMsg, "passcode") || strstr(errorMsg, "MFA") ||
                strstr(errorMsg, "authentication failed")) {
                printf("WARN: TOTP attempt %d failed - retrying with next code\n", i + 1);

                snowflake_set_attribute(sf, SF_CON_USER, mfa_user);
                snowflake_set_attribute(sf, SF_CON_PASSWORD, mfa_password);
                snowflake_set_attribute(sf, SF_CON_CLIENT_REQUEST_MFA_TOKEN, &(sf_bool){1});
                
                continue;
            } else {
                printf("WARN: Non-TOTP error on attempt %d, stopping: %s\n", i + 1, lastError);
                break;
            }
        }
    }
    freeTotpCodes(totpCodes);
    snowflake_term(sf);
    printf("ERROR: Failed to connect with any TOTP codes. Last error: %s\n", lastError);
    fail();
}
