jobs:
- job: osx
  pool:
    vmImage: macOS-10.14
  timeoutInMinutes: 360
  variables:
    CONFIG: {{ config }}
    ARROW_VERSION: {{ arrow.no_rc_version }}
    UPLOAD_PACKAGES: False
  steps:
  - script: |
      echo "Removing homebrew from Azure to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew
    displayName: Remove homebrew

  - bash: |
      echo "##vso[task.prependpath]$CONDA/bin"
      sudo chown -R $USER $CONDA
    displayName: Add conda to PATH

  - script: |
      source activate base
      conda install -n base -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
    displayName: 'Add conda-forge-ci-setup=2'

  - script: |
      git clone --no-checkout {{ arrow.remote }} arrow
      git -C arrow fetch -t {{ arrow.remote }} {{ arrow.branch }}
      git -C arrow checkout FETCH_HEAD
      git -C arrow submodule update --init --recursive
    displayName: Clone arrow

  - script: |
      source activate base
      echo "Configuring conda."

      setup_conda_rc ./ ./ ./.ci_support/${CONFIG}.yaml
      export CI=azure
      source run_conda_forge_build_setup
      conda update --yes --quiet --override-channels -c conda-forge -c defaults --all
    displayName: Configure conda and conda-build
    workingDirectory: arrow/dev/tasks/conda-recipes
    env: {
      OSX_FORCE_SDK_DOWNLOAD: "1"
    }

  - script: |
      source activate base
      mangle_compiler ./ ./ ./.ci_support/${CONFIG}.yaml
    workingDirectory: arrow/dev/tasks/conda-recipes
    displayName: Mangle compiler

  - script: |
      source activate base
      make_build_number ./ ./ ./.ci_support/${CONFIG}.yaml
    workingDirectory: arrow/dev/tasks/conda-recipes
    displayName: Generate build number clobber file

  - script: |
      source activate base
      conda build arrow-cpp parquet-cpp pyarrow \
        -m ./.ci_support/${CONFIG}.yaml \
        --clobber-file ./.ci_support/clobber_${CONFIG}.yaml \
        --output-folder ./build_artifacts
    workingDirectory: arrow/dev/tasks/conda-recipes
    displayName: Build recipes

  # Using github release tries to find a common ancestor between the
  # currently pushed tag and the latest tag of the github repository
  # (don't know why).
  # The tag upload took 43 minutes because of this scan, so use an
  # alternative upload script.
  - script: |
      source activate base
      conda install -y click github3.py jinja2 jira pygit2 ruamel.yaml setuptools_scm toolz
      python arrow/dev/tasks/crossbow.py \
        --queue-path . \
        --queue-remote {{ queue_remote_url }} \
        upload-artifacts \
        --sha {{ task.branch }} \
        --tag {{ task.tag }} \
        --pattern "arrow/dev/tasks/conda-recipes/build_artifacts/osx-64/*.tar.bz2"
    env:
      CROSSBOW_GITHUB_TOKEN: $(CROSSBOW_GITHUB_TOKEN)
    displayName: Upload packages as a GitHub release

  {% if arrow.branch == 'master' %}
  # Upload to custom anaconda channel
  - script: |
      source activate base
      conda install -y anaconda-client
      anaconda -t $(CROSSBOW_ANACONDA_TOKEN) upload --force build_artifacts/osx-64/*.tar.bz2
    displayName: Upload packages to Anaconda
    workingDirectory: arrow/dev/tasks/conda-recipes
  {% endif %}
