name: aws-lc integration tests
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true
env:
  CC: gcc
jobs:
  haproxy:
    runs-on: ubuntu-latest
    steps:
      - name: Install OS Dependencies
        run: |
          sudo apt-get -y --no-install-recommends install cmake gcc ninja-build golang make
      - uses: actions/checkout@v3
      - name: Run integration build
        run: |
          ./tests/ci/integration/run_haproxy_integration.sh
  grpc:
    env:
      DEBIAN_FRONTEND: noninteractive
      TZ: Etc/UTC
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
      options: --sysctl=net.ipv6.conf.all.disable_ipv6=0
    steps:
      - name: Install OS Dependencies
        run: |
          apt-get update && apt-get -y --no-install-recommends install cmake gcc g++ ninja-build golang make python3 python3-sphinx autoconf libtool pkg-config git libc++-dev
      - uses: actions/checkout@v3
      - name: Run integration build
        run: |
          ./tests/ci/integration/run_grpc_integration.sh
  tcpdump:
    runs-on: ubuntu-latest
    steps:
      - name: Install OS Dependencies
        run: |
          sudo apt-get update && sudo apt-get -y --no-install-recommends install cmake gcc ninja-build golang make libpcap-dev binutils-dev
      - uses: actions/checkout@v3
      - name: Run integration build
        run: |
          ./tests/ci/integration/run_tcpdump_integration.sh
