# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

git:
  depth: 1
language: c

# Install additional dependencies first. Enable brew update when you need to find other softwares (like quilt) on xcode10.3
addons:
  homebrew:
    update: false
    packages:
      - ninja

# Build matrix: test OSX with two versions of xcode/clang
os: osx
osx_image:
  - xcode10.3
  - xcode12u
compiler: clang

# Run the script which contains all the build logic
script:
  - cmake --version
  - tests/ci/run_posix_tests.sh

# Setting environment variables.
env:
  - RSA_TEST_THREADS_LIMIT=1024
