FROM redhat/ubi8

RUN dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
RUN dnf upgrade -y
RUN yum -y update
RUN yum install -y yum-utils

# dependencies & tools
RUN yum install -y wget gettext zip bzip2 cmake python39 git gcc-c++ libstdc++-static unixODBC unixODBC-devel vim jq re2 re2-devel automake autoconf libtool perl-IPC-Cmd perl-Digest-SHA
RUN ln -s /usr/bin/python3.9 /usr/bin/python
RUN python -m pip install --upgrade pip
RUN pip install awscli

# valgrind
RUN cd /tmp && wget https://sourceware.org/pub/valgrind/valgrind-3.23.0.tar.bz2 && tar xvf valgrind-3.23.0.tar.bz2 && cd valgrind-3.23.0 && ./configure && make && make install

#cppunit
RUN cd /tmp && git clone git://anongit.freedesktop.org/git/libreoffice/cppunit &&\
    cd cppunit &&\
    git checkout tags/cppunit-1.15.1 -b v1.15.1 &&\
    ./autogen.sh &&\
    ./configure CXXFLAGS="-std=c++11" &&\
    make && make install &&\
    cp /usr/local/lib/libcppunit* /usr/lib64

# Java
RUN yum -y install java-17-openjdk-devel

# gosu
RUN curl -o /usr/local/bin/gosu -SL "https://github.com/tianon/gosu/releases/download/1.11/gosu-arm64"
RUN chmod +x /usr/local/bin/gosu
COPY scripts/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

# workspace
RUN mkdir -p /home/user
RUN chmod 777 /home/user
WORKDIR /home/user

