MACOSX_DEPLOYMENT_TARGET:
- '10.9'
boost_cpp:
- '1.72'
bzip2:
- '1'
c_compiler:
- clang
c_compiler_version:
- '9'
channel_sources:
- conda-forge,defaults
channel_targets:
- conda-forge main
cxx_compiler:
- clangxx
cxx_compiler_version:
- '9'
glog:
- 0.4.0
grpc_cpp:
- '1.27'
libprotobuf:
- '3.11'
lz4_c:
- 1.8.3
macos_machine:
- x86_64-apple-darwin13.4.0
macos_min_version:
- '10.9'
pin_run_as_build:
  boost-cpp:
    max_pin: x.x.x
  bzip2:
    max_pin: x
  grpc-cpp:
    max_pin: x.x
  lz4-c:
    max_pin: x.x.x
  python:
    min_pin: x.x
    max_pin: x.x
  zlib:
    max_pin: x.x
  zstd:
    max_pin: x.x.x
python:
- '3.6'
snappy:
- '1'
zlib:
- '1.2'
zstd:
- 1.4.4
