boost_cpp:
- '1.72'
bzip2:
- '1'
c_compiler:
- vs2015
channel_sources:
- conda-forge,defaults
channel_targets:
- conda-forge main
cxx_compiler:
- vs2015
glog:
- 0.4.0
grpc_cpp:
- '1.27'
libprotobuf:
- '3.11'
lz4_c:
- 1.8.3
pin_run_as_build:
  boost-cpp:
    max_pin: x.x.x
  bzip2:
    max_pin: x
  grpc-cpp:
    max_pin: x.x
  lz4-c:
    max_pin: x.x.x
  python:
    min_pin: x.x
    max_pin: x.x
  vc:
    max_pin: x
  zlib:
    max_pin: x.x
  zstd:
    max_pin: x.x.x
python:
- '3.7'
snappy:
- '1'
vc:
- '14'
zip_keys:
- - python
  - vc
  - c_compiler
  - cxx_compiler
zlib:
- '1.2'
zstd:
- 1.4.4
