#ifndef SF_LIB_COMMON_H
#define SF_LIB_COMMON_H

typedef enum SF_RET_CODE
{
    /* COMMON CODES */
    SF_RET_CODE_SUCCESS,
    SF_RET_CODE_ERROR,

    /* TREEMAP SPECIFIC CODES */
    SF_RET_CODE_BAD_INDEX,

    /* RBTREE SPECIFIC CODES */
    SF_RET_CODE_NODE_NOT_FOUND,
    SF_RET_CODE_DUPLICATES
}SF_RET_CODE;

#endif /* SF_LIB_COMMON_H */