coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
comment:
  require_base: false
  require_changes: false
  require_head: true
  hide_project_coverage: false
