# CMake generated Testfile for 
# Source directory: /mnt/host/tests
# Build directory: /mnt/host/cmake-build/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_unit_connect_parameters "test_unit_connect_parameters")
add_test(valgrind_test_unit_connect_parameters "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_unit_connect_parameters")
add_test(test_unit_logger "test_unit_logger")
add_test(valgrind_test_unit_logger "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_unit_logger")
add_test(test_connect "test_connect")
add_test(valgrind_test_connect "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_connect")
add_test(test_connect_negative "test_connect_negative")
add_test(valgrind_test_connect_negative "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_connect_negative")
add_test(test_bind_params "test_bind_params")
add_test(valgrind_test_bind_params "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_bind_params")
add_test(test_bind_named_params "test_bind_named_params")
add_test(valgrind_test_bind_named_params "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_bind_named_params")
add_test(test_change_current "test_change_current")
add_test(valgrind_test_change_current "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_change_current")
add_test(test_select1 "test_select1")
add_test(valgrind_test_select1 "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_select1")
add_test(test_check_ctypes "test_check_ctypes")
add_test(valgrind_test_check_ctypes "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_check_ctypes")
add_test(test_crud "test_crud")
add_test(valgrind_test_crud "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_crud")
add_test(test_error_handlings "test_error_handlings")
add_test(valgrind_test_error_handlings "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_error_handlings")
add_test(test_large_result_set "test_large_result_set")
add_test(valgrind_test_large_result_set "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_large_result_set")
add_test(test_transaction "test_transaction")
add_test(valgrind_test_transaction "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_transaction")
add_test(test_ping_pong "test_ping_pong")
add_test(valgrind_test_ping_pong "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_ping_pong")
add_test(test_stmt_with_bad_connect "test_stmt_with_bad_connect")
add_test(valgrind_test_stmt_with_bad_connect "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_stmt_with_bad_connect")
add_test(test_binary "test_binary")
add_test(valgrind_test_binary "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_binary")
add_test(test_bool "test_bool")
add_test(valgrind_test_bool "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_bool")
add_test(test_null "test_null")
add_test(valgrind_test_null "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_null")
add_test(test_number "test_number")
add_test(valgrind_test_number "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_number")
add_test(test_variant "test_variant")
add_test(valgrind_test_variant "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_variant")
add_test(test_time "test_time")
add_test(valgrind_test_time "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_time")
add_test(test_timestamp_ntz "test_timestamp_ntz")
add_test(valgrind_test_timestamp_ntz "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_timestamp_ntz")
add_test(test_timestamp_ltz "test_timestamp_ltz")
add_test(valgrind_test_timestamp_ltz "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_timestamp_ltz")
add_test(test_timestamp_tz "test_timestamp_tz")
add_test(valgrind_test_timestamp_tz "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_timestamp_tz")
add_test(test_timezone "test_timezone")
add_test(valgrind_test_timezone "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_timezone")
add_test(test_adjust_fetch_data "test_adjust_fetch_data")
add_test(valgrind_test_adjust_fetch_data "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_adjust_fetch_data")
add_test(test_issue_76 "test_issue_76")
add_test(valgrind_test_issue_76 "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_issue_76")
add_test(test_column_fetch "test_column_fetch")
add_test(valgrind_test_column_fetch "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_column_fetch")
add_test(test_native_timestamp "test_native_timestamp")
add_test(valgrind_test_native_timestamp "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_native_timestamp")
add_test(test_unit_jwt "test_unit_jwt")
add_test(valgrind_test_unit_jwt "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_unit_jwt")
add_test(test_unit_cipher_stream_buf "test_unit_cipher_stream_buf")
add_test(valgrind_test_unit_cipher_stream_buf "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_unit_cipher_stream_buf")
add_test(test_unit_cred_renew "test_unit_cred_renew")
add_test(valgrind_test_unit_cred_renew "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_unit_cred_renew")
add_test(test_unit_file_metadata_init "test_unit_file_metadata_init")
add_test(valgrind_test_unit_file_metadata_init "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_unit_file_metadata_init")
add_test(test_unit_file_type_detect "test_unit_file_type_detect")
add_test(valgrind_test_unit_file_type_detect "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_unit_file_type_detect")
add_test(test_unit_stream_splitter "test_unit_stream_splitter")
add_test(valgrind_test_unit_stream_splitter "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_unit_stream_splitter")
add_test(test_unit_thread_pool "test_unit_thread_pool")
add_test(valgrind_test_unit_thread_pool "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_unit_thread_pool")
add_test(test_unit_base64 "test_unit_base64")
add_test(valgrind_test_unit_base64 "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_unit_base64")
add_test(test_unit_proxy "test_unit_proxy")
add_test(valgrind_test_unit_proxy "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_unit_proxy")
add_test(test_perf_string_reads_and_writes "test_perf_string_reads_and_writes")
add_test(valgrind_test_perf_string_reads_and_writes "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_perf_string_reads_and_writes")
add_test(test_perf_column_evaluation "test_perf_column_evaluation")
add_test(valgrind_test_perf_column_evaluation "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_perf_column_evaluation")
add_test(test_perf_type_conversion "test_perf_type_conversion")
add_test(valgrind_test_perf_type_conversion "valgrind" "--tool=memcheck" "--leak-check=full" "--error-exitcode=1" "--suppressions=/mnt/host/tests/utils/valgrind_suppressions.txt" "./test_perf_type_conversion")
subdirs(test_bind_datastructures)
