name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - develop
      - feature/**

env:
  UBSAN_OPTIONS: print_stacktrace=1

jobs:
  posix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - toolset: gcc-4.8
            os: ubuntu-18.04
            install: g++-4.8
          - toolset: gcc-5
            os: ubuntu-18.04
            install: g++-5
          - toolset: gcc-6
            os: ubuntu-18.04
            install: g++-6
          - toolset: gcc-7
            os: ubuntu-18.04

# gcc-8 variant=release crashes
#         - toolset: gcc-8
#           os: ubuntu-18.04
#           install: g++-8

          - toolset: gcc-9
            os: ubuntu-20.04
          - toolset: gcc-10
            os: ubuntu-20.04
            install: g++-10
          - toolset: gcc-11
            os: ubuntu-20.04
            install: g++-11
          - toolset: gcc-12
            os: ubuntu-22.04
            install: g++-12
          - toolset: clang
            compiler: clang++-3.9
            os: ubuntu-18.04
            install: clang-3.9
          - toolset: clang
            compiler: clang++-4.0
            os: ubuntu-18.04
            install: clang-4.0
          - toolset: clang
            compiler: clang++-5.0
            os: ubuntu-18.04
            install: clang-5.0
          - toolset: clang
            compiler: clang++-6.0
            os: ubuntu-18.04
            install: clang-6.0
          - toolset: clang
            compiler: clang++-7
            os: ubuntu-18.04
            install: clang-7
          - toolset: clang
            compiler: clang++-8
            os: ubuntu-20.04
            install: clang-8
          - toolset: clang
            compiler: clang++-9
            os: ubuntu-20.04
            install: clang-9
          - toolset: clang
            compiler: clang++-10
            os: ubuntu-20.04
            install: clang-10
          - toolset: clang
            compiler: clang++-11
            os: ubuntu-20.04
            install: clang-11
          - toolset: clang
            compiler: clang++-12
            os: ubuntu-20.04
            install: clang-12
          - toolset: clang
            compiler: clang++-13
            os: ubuntu-22.04
            install: clang-13
          - toolset: clang
            compiler: clang++-14
            os: ubuntu-22.04
            install: clang-14
          - toolset: clang
            os: macos-11

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        if: matrix.install
        run: sudo apt install ${{matrix.install}}

      - name: Setup Boost
        run: |
          echo GITHUB_REPOSITORY: $GITHUB_REPOSITORY
          echo GITHUB_BASE_REF: $GITHUB_BASE_REF
          echo GITHUB_REF: $GITHUB_REF
          REF=${GITHUB_BASE_REF:-$GITHUB_REF}
          REF=${REF#refs/heads/}
          echo REF: $REF
          BOOST_BRANCH=develop && [ "$REF" == "master" ] && BOOST_BRANCH=master || true
          echo BOOST_BRANCH: $BOOST_BRANCH
          cd ..
          git clone -b $BOOST_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
          cd boost-root
          cp -r $GITHUB_WORKSPACE/* tools/quickbook
          git submodule update --init tools/boostdep
          python tools/boostdep/depinst/depinst.py --git_args "--jobs 3" ../tools/quickbook
          ./bootstrap.sh
          ./b2 -d0 headers

      - name: Create user-config.jam
        if: matrix.compiler
        run: |
          echo "using ${{matrix.toolset}} : : ${{matrix.compiler}} ;" > ~/user-config.jam

      - name: Run tests
        run: |
          cd ../boost-root
          ./b2 -j3 tools/quickbook/test toolset=${{matrix.toolset}} variant=debug,release

  windows:
    strategy:
      fail-fast: false
      matrix:
        include:
          - toolset: msvc-14.0
            os: windows-2019
          - toolset: msvc-14.2
            os: windows-2019
          - toolset: msvc-14.3
            os: windows-2022

# The test Jamfile doesn't work with the clang-win toolset for some reason
#         - toolset: clang-win
#           os: windows-2022

# gcc-8 variant=release crashes
#         - toolset: gcc
#           os: windows-2019

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Boost
        shell: cmd
        run: |
          echo GITHUB_BASE_REF: %GITHUB_BASE_REF%
          echo GITHUB_REF: %GITHUB_REF%
          if "%GITHUB_BASE_REF%" == "" set GITHUB_BASE_REF=%GITHUB_REF%
          set BOOST_BRANCH=develop
          for /f %%i in ("%GITHUB_BASE_REF%") do if "%%~nxi" == "master" set BOOST_BRANCH=master
          echo BOOST_BRANCH: %BOOST_BRANCH%
          cd ..
          git clone -b %BOOST_BRANCH% --depth 1 https://github.com/boostorg/boost.git boost-root
          cd boost-root
          xcopy /s /e /q %GITHUB_WORKSPACE% tools\quickbook\
          git submodule update --init tools/boostdep
          python tools/boostdep/depinst/depinst.py --git_args "--jobs 3" ../tools/quickbook
          cmd /c bootstrap
          b2 -d0 headers

      - name: Run tests
        shell: cmd
        run: |
          cd ../boost-root
          b2 -j3 tools/quickbook/test toolset=${{matrix.toolset}} variant=debug,release embed-manifest-via=linker
