version: 0.2
phases:
  build:
    commands:
    - cd ..
    - zip -r latestSnapshot.zip aws-sdk-cpp
    - mv latestSnapshot.zip $CODEBUILD_SRC_DIR
    - cd $CODEBUILD_SRC_DIR
artifacts:
  files:
    - latestSnapshot.zip
