name: Code quality

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - '**'

jobs:
  check-warnings:
    name: Extra-Warnings-Linux
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [ 'Release' ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13.3'
          architecture: 'x64'
      - name: Restore cached deps
        id: cache-restore-deps
        uses: actions/cache/restore@v4
        with:
          path: dep-cache
          key: ${{ matrix.build_type }}-${{ github.event.pull_request.base.sha }}-Linux-dep-cache
        if: github.event_name == 'pull_request'
      - name: Build
        shell: bash
        env:
          USE_EXTRA_WARNINGS: "true"
          BUILD_TYPE: ${{ matrix.build_type }}
        run: ci/build_linux.sh
      - name: Restore cached warnings
        id: cache-restore-warnings
        uses: actions/cache/restore@v4
        with:
          path: warnings.json
          key: ${{ github.event.pull_request.base.sha }}-compile-warnings
        if: github.event_name == 'pull_request'
      - name: Use cached warnings as a baseline
        shell: bash
        run: cp warnings.json ./ci/scripts/warnings_baseline.json
        if: steps.cache-restore-warnings.outputs.cache-hit == 'true'
      - name: Warning report
        shell: bash
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: ci/scripts/warning_report.sh
      - name: Upload build log
        uses: actions/upload-artifact@v4
        with:
          name: build log
          path: build.log
      - name: Upload warning report
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.md
      - name: Upload warnings
        uses: actions/upload-artifact@v4
        with:
          name: warnings
          path: warnings.json
      - name: Cache warnings
        id: cache-save-warnings
        uses: actions/cache/save@v4
        with:
          path: warnings.json
          key: ${{ github.sha }}-compile-warnings
        if: github.ref_name == github.event.repository.default_branch

